# Generated by Django 5.2.7 on 2025-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
    ]
