# Generated by Django 5.2.7 on 2025-11-24 17:05

import datetime
import random

from django.db import migrations

def ia(task):
    days = random.randint(1, 21)
    return task.created_at + datetime.timedelta(days=days)


def set_due_date(apps, schemaeditor):
    Task = apps.get_model("tasks", "task")
    for task in Task.objects.filter(due_date=None):
        task.due_date = ia(task)
        task.save()


def undo_set_due_date(apps, schemaeditor):
    Task = apps.get_model("tasks", "task")
    for task in Task.objects.all():
        task.due_date = None
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.RunPython(set_due_date, undo_set_due_date),
    ]
