# Generated by Django 5.2.7 on 2025-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_urgent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("representation", models.CharField(max_length=18)),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-urgent"]},
        ),
    ]
