# Generated by Django 5.2.7 on 2025-11-23 13:28

from django.db import migrations

SQL_INSERT_PRIORITIES = (
    "INSERT INTO tasks_priority (id, representation, level) VALUES"
    "    ('LOW', 'Baja', -10),"
    "    ('NOR', 'Normal', 0),"
    "    ('URG', 'Urgente', 10),"
    "    ('CRI', 'Crítica', 100)"
    ";"
    )

SQL_DELETE_PRIORITIES = "DELETE FROM tasks_priority;"

class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_priority_alter_task_options"),
    ]

    operations = [
        migrations.RunSQL(SQL_INSERT_PRIORITIES, SQL_DELETE_PRIORITIES),
        ]
