# Generated by Django 5.2.7 on 2025-11-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_priority_fill_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                default="NOR",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="tasks.priority",
            ),
        ),
    ]
