# Generated by Django 5.2.7 on 2025-11-23 19:53

from django.db import migrations

def set_priority(apps, schema_editor):
    # No podemos usar Task directamente, porque puede
    # que a estas alturas exista una versión posterior a la
    # que espera la migración. Por eso tenemos que viajar en el tiempo
    # y cargar el modelo que se corresponda con el momento histórico
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.filter(urgent=True):
        task.priority_id = 'URG'
        task.save()


def undo_set_priority(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")  # Lo mismo
    for task in Task.objects.exclude(priority='NOR'):
        task.priority_id = 'NOR'
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_priority"),
    ]

    operations = [
        migrations.RunPython(set_priority, undo_set_priority),
        ]
