# Generated by Django 5.2.7 on 2025-11-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_set_priority_from_urgent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority__level"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="urgent",
        ),
    ]
